version: '3.8'

# define os containers utilizados
services:
  we_movies:
    image: we_movies_image:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: we_movies
    networks:
      - compose_network
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}

# define as redes para comunicação entre os containers
networks:
  compose_network:
    driver: bridge


# para rodar o docker-compose.yml, execute o comando:
# docker compose up